using System;
using System.Collections.Generic;
using System.Text;

namespace EVF.Helper.Components
{
    public static class MessageValue
    {
        public const string UserRoleIsEmpty = "กรุณาติดต่อเจ้าหน้าที่ เพื่อเปิดสิทธิ์การใช้งาน";
        public const string LoginFailed = "ขออภัย Username หรือ Password ไม่ถูกต้อง";
        public const string Unauthorized = "กรุณาเข้าสู่ระบบ เพื่อใช้งาน";
        public const string InternalServerError = "ระบบเกิดข้อผิดพลาด กรุณาติดต่อเจ้าหน้าที่";
        public const string GradePointIncorrect = "กรุณากรอก ช่วงคะแนนให้ถูกต้อง";
        public const string GradePointOverRange = "กรุณาระบุช่วงคะแนน 0 ถึง 100 เท่านั้น";
        public const string CriteriaOverScore = "ขออภัย คะแนนเต็ม ทั้งหมดรวมกัน ต้องไม่น้อยกว่า หรือ มากกว่า 100 คะแนน";
        public const string CriteriaKpiGroupEmpty= "กรุณาเลือก กลุ่มการประเมิน";
        public const string CriteriaItemScoreGreatethanScoreGroup = "ขออภัย คะแนนกลุ่มการประเมิน ไม่สามารถน้อยกว่าหรือมากกว่า คะแนนหัวข้อการประเมินรวมกันได้";
        public const string EvaluationRejectTaskIsAction = "ขออภัย ไม่สามารถปฎิเสธงานที่ทำการประเมินแล้วได้";
        public const string KpiGroupOverFiftySapFields = "ขออภัย ไม่สามารถสร้างกลุ่มการประเมิน เกิน 50 กลุ่มได้";
        public const string KpiGroupItemsDuplicates = "ขออภัย ไม่สามารถเลือกกลุ่มการประเมินซ้ำกันได้";
        public const string IsUseMessageFormat = "ขออภัย ไม่สามารถแก้ไข หรือ ลบ {0} เนื่องจากมีการนำไปใช้งานแล้ว";
        public const string HttpBadRequestMessage = "กรุณา กรอกข้อมูลให้ถูกต้อง";
        public const string DuplicateEvaluationAssign = "ขออภัย ไม่สามารถเลือกผู้ประเมินซ้ำกันได้";
        public const string KpiMessage = "หัวข้อการประเมิน";
        public const string KpiGroupMessage = "กลุ่มการประเมิน";
        public const string CriteriaMessage = "หลักเกณฑ์";
        public const string EvaluationTemplateMessage = "Template แบบประเมิน";
        public const string LevelPointMessage = "ระดับคะแนน";
        public const string GradeMessage = "เกณฑ์การประเมิน";
        public const string WorkflowFiloEvaluationProcess = "ประเมินผู้ขาย {0}";
        public const string StatusInvalidAction = "ไม่สามารถส่งอนุมัติได้ เนื่องจากใบประเมิน อยู่ในสถานะ {0}";
        public const string EvaluatorEmpty = "กรุณาเลือก ผู้ประเมิน หรือกลุ่มผู้ประเมิน";
        public const string PleaseSelectedEvaluationTemplate = "กรุณาเลือก Template แบบประเมิน";
        public const string PleaseSelectedVendor = "กรุณาเลือก ผู้ขาย";
        public const string PleaseSelectedWeightingKey = "กรุณาเลือก ประเภทผู้ขาย";
        public const string PleaseSelectedCompany = "กรุณาเลือก บริษัท";
        public const string PleaseSelectedPurchaseOrg = "กรุณาเลือก กลุ่มจัดซื้อ";
        public const string PleaseSelectedPeriod = "กรุณาเลือก รอบการประเมิน";
        public const string PleaseSelectedEvaluatorPurchase = "กรุณาเลือก จัดซื้อผู้ประเมิน";
        public const string PleaseSelectedKpiGroup = "กรุณาเลือก กลุ่มการประเมิน";
        public const string PleaseSelectedCriteria = "กรุณาเลือก หลักเกณฑ์";
        public const string PleaseSelectedGrade = "กรุณาเลือก เกณฑ์การประเมิน";
        public const string PleaseSelectedLevelPoint = "กรุณาเลือก ระดับคะแนน";
        public const string PleaseSelectedStartDate = "กรุณาเลือก วันที่เริ่มต้น";
        public const string PleaseSelectedEndDate = "กรุณาเลือก วันที่สิ้นสุด";
        public const string PleaseSelectedCondition = "กรุณาเลือก เงื่อนไข";
        public const string PleaseSelectedAssignTo = "กรุณาเลือก จัดซื้อ";
        public const string PleaseSelectedPurGroup = "กรุณาเลือก PurGroup";
        public const string PleaseFillCriteriaName = "กรุณากรอก ชื่อหลักเกณฑ์";
        public const string PleaseSelectedToUser = "กรุณาเลือก ผู้ประเมิน";
        public const string PleaseSelectedApproval = "กรุณาเลือก ผู้อนุัมติ";
        public const string PleaseFillEvaluationTemplateName = "กรุณากรอก ชื่อ Template แบบประเมิน";
        public const string PleaseFillScore = "กรุณากรอก คะแนน";
        public const string CriteriaNameOverLength = "ขออภัย ชื่อหลักเกณฑ์ ความยาวต้องไม่เกิน 200 ตัวอักษร";
        public const string EvaluationTemplateNameOverLength = "ขออภัย ชื่อ Template แบบประเมิน ความยาวต้องไม่เกิน 200 ตัวอักษร";
        public const string EvaluationLogSaveValidate = "ขออภัย ไม่สามารถบันทึกการประเมินได้ กรุณาประเมินให้ครบทุกข้อ";
        public const string PleaseFillStartPoint = "กรุณากรอก คะแนนเริ่มต้น";
        public const string PleaseFillEndPoint = "กรุณากรอก คะแนนสิ้นสุด";
        public const string PleaseFillGradeNameTh = "กรุณากรอก ชื่อเกรดภาษาไทย";
        public const string PleaseFillGradeNameEn = "กรุณากรอก ชื่อเกรดภาษาอังกฤษ";
        public const string PleaseFillGrade = "กรุณากรอกชื่อ เกณฑ์การประเมิน";
        public const string GradeOverLength = "ขออภัยชื่อเกณฑ์การประเมิน ความยาวต้องไม่เกิน 200 ตัวอักษร";
        public const string GradeNameOverLength = "ขออภัยชื่อเกรด ความยาวต้องไม่เกิน 100 ตัวอักษร";
        public const string PleaseFillKpiGroupNameTh = "กรุณากรอก ชื่อกลุ่มการประเมินภาษาไทย";
        public const string PleaseFillKpiGroupNameEn = "กรุณากรอก ชื่อกลุ่มการประเมินภาษาอังกฤษ";
        public const string PleaseFillKpiGroupShortTextTh = "กรุณากรอก ชื่อย่อกลุ่มการประเมินภาษาไทย";
        public const string PleaseFillKpiGroupShortTextEn = "กรุณากรอก ชื่อย่อกลุ่มการประเมินภาษาอังกฤษ";
        public const string KpiGroupShortTextOverLength = "ขออภัยชื่อย่อกลุ่มการประเมิน ความยาวต้องไม่เกิน 40 ตัวอักษร";
        public const string KpiGroupNameOverLength = "ขออภัยชื่อกลุ่มการประเมิน ความยาวต้องไม่เกิน 200 ตัวอักษร";
        public const string PleaseFillKpiNameTh = "กรุณากรอก ชื่อหัวข้อการประเมินภาษาไทย";
        public const string PleaseFillKpiNameEn = "กรุณากรอก ชื่อหัวข้อการประเมินภาษาอังกฤษ";
        public const string PleaseFillKpiShortTextTh = "กรุณากรอก ชื่อย่อหัวข้อการประเมินภาษาไทย";
        public const string PleaseFillKpiShortTextEn = "กรุณากรอก ชื่อย่อหัวข้อการประเมินภาษาอังกฤษ";
        public const string KpiShortTextOverLength = "ขออภัยชื่อย่อหัวข้อการประเมิน ความยาวต้องไม่เกิน 40 ตัวอักษร";
        public const string KpiNameOverLength = "ขออภัยชื่อหัวข้อการประเมิน ความยาวต้องไม่เกิน 200 ตัวอักษร";
        public const string PleaseFillLevelPointName = "กรุณากรอก ชื่อระดับคะแนน";
        public const string PleaseSelectedLevelPointCalculate = "กรุณาเลือกประเภทผู้ขายเพื่อ กำหนดสูตรคำนวน";
        public const string LevelPointNameOverLength = "ขออภัยชื่อระดับคะแนน ความยาวต้องไม่เกิน 100 ตัวอักษร";
        public const string PleaseFillPeriodItemName = "กรุณากรอก ชื่อรอบการประเมิน";
        public const string PleaseFillStartEvaDate = "กรุณาระบุ วันที่เริ่มต้นการประเมิน";
        public const string PleaseFillEndEvaDate = "กรุณาระบุ วันที่สิ้นสุดการประเมิน";
        public const string PeriodItemNameOverLength = "ขออภัยชื่อรอบการประเมิน ความยาวต้องไม่เกิน 80 ตัวอักษร";
        public const string PleaseSelectedYear = "กรุณาเลือกปี";
        public const string PleaseFillPeriodName = "กรุณากรอก ชื่อการประเมิน";
        public const string PeriodNameOverLength = "ขออภัยชื่อการประเมิน ความยาวต้องไม่เกิน 150 ตัวอักษร";
        public const string PleaseFillPurchasePercentage = "กรุณากรอกสัดส่วนคะแนน จัดซื้อ";
        public const string PleaseFillUserPercentage = "กรุณากรอกสัดส่วนคะแนน ผู้ประเมิน";
        public const string PleaseFillEvaluatorGroupName = "กรุณากรอก ชื่อกลุ่มผู้ประเมิน";
        public const string PleaseFillPurchaseOrgCode = "กรุณากรอก รหัสกลุ่มจัดซื้อ";
        public const string PleaseFillPurchaseOrgName = "กรุณากรอก ชื่อกลุ่มจัดซื้อ";
        public const string PurchaseOrgCodeOverLength = "ขออภัยรหัสกลุ่มจัดซื้อ ความยาวต้องไม่เกิน 4 ตัวอักษร";
        public const string PurchaseOrgNameOverLength = "ขออภัยชื่อกลุ่มจัดซื้อ ความยาวต้องไม่เกิน 200 ตัวอักษร";
    }
}
